apiVersion: v1
kind: Pod
metadata: 
    name: nginx-pod
    labels: 
        env: prod
spec: 
    containers:
        - name: nginx-demoapp
           image: nginx
       ports:
       - containerPort: 80
